/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package samoloty_ruch;

import java.util.ArrayList;

/**
 *
 * @author Seba
 */
public class GUISymulacja extends javax.swing.JFrame {

    
    
    static ArrayList <Plane> ghangar = new ArrayList <>();
    static ArrayList <Airport> gAirports = new ArrayList <>();
    static boolean startAnimation = false ;
    
    /**
     * Creates new form GUISymulacja
     */
    public GUISymulacja() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        generatePlanes = new javax.swing.JButton();
        airport = new javax.swing.JButton();
        jPanel1 = new MyPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        generatePlanes.setText("Generuj samoloty");
        generatePlanes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatePlanesActionPerformed(evt);
            }
        });

        airport.setText("Lotnisko");
        airport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 739, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
        );

        jButton1.setText("Symulacja");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Start");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Stop");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(generatePlanes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(airport, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 514, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(135, 135, 135))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(airport)
                    .addComponent(jButton1)
                    .addComponent(generatePlanes))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // GENERUJ SAMOLOTY //
    private void generatePlanesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatePlanesActionPerformed
        Plane S1;
        S1 = new Plane();
        
        System.out.println("S1: "+S1);
        S1.setSa(GUISymulacja.gAirports.get(0));
        S1.setX(GUISymulacja.gAirports.get(0).getX()*1.0);
        S1.setY(GUISymulacja.gAirports.get(0).getY()*1.0);
        S1.setTa(GUISymulacja.gAirports.get(1));
        
//        GUISymulacja.gAirports.get(0)
//        GUISymulacja.gAirports.get(0)
        ghangar.add(S1);
        jPanel1.repaint();
//            for(int i=1; i<100; i++){
//                S1 = new Plane(i);
//                ghangar.add(S1);
//                System.out.println("S1"+S1);
//                System.out.println("airports: "+GUISymulacja.gAirports);
//            }

    }//GEN-LAST:event_generatePlanesActionPerformed
    // GENERUJ LOTNISKO //
    private void airportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airportActionPerformed
        Airport Airport1;
        Airport1 = new Airport(1, jPanel1);
        System.out.println(""+Airport1);
        GUISymulacja.gAirports.add(Airport1); // dodanie obiektu S1 do globalnego statycznego kontenera
        jPanel1.repaint();
    }//GEN-LAST:event_airportActionPerformed
    // SYMULACJA //
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    	ghangar=new ArrayList();
        
        // tworzenie pierwszego lotniska
        Airport Airport1;
        Airport1 = new Airport(1, jPanel1);
        System.out.println(""+Airport1);
        Airport1.setY(50);
        Airport1.setX(50);
   
        GUISymulacja.gAirports.add(Airport1); // dodanie obiektu S1 do globalnego statycznego kontenera
        jPanel1.repaint();
        
        // tworzenie drugiego lotniska
        Airport Airport2;
        Airport2 = new Airport(2, jPanel1);
        System.out.println(""+Airport2);
        Airport2.setY(200);
        Airport2.setX(500);
        
        GUISymulacja.gAirports.add(Airport2); // dodanie obiektu S1 do globalnego statycznego kontenera
        jPanel1.repaint();
        
        
        Plane p1;
        p1 = new Plane(1);
        p1.setSa(Airport1);
        p1.setX(Airport1.getX()*1.0);
        p1.setY(Airport1.getY()*1.0);
        p1.setTa(Airport2);
        ghangar.add(p1);
        System.out.println("hangar: "+ghangar);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    // START //
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Timer t1 = new Timer(jPanel1);
        startAnimation=true;
        t1.start();
   // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    // STOP //
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        startAnimation =false;         // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    
    /**+
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUISymulacja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUISymulacja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUISymulacja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUISymulacja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUISymulacja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton airport;
    private javax.swing.JButton generatePlanes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
